apiVersion: v1
kind: Service
metadata:
  name: filer
  namespace: micro
  labels:
    app: filer
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 31888
      port: 8888
      targetPort: 8888
  selector:
    app: filer
