# ATTENTION: this file is kept here for backwards compatibility reasons
# use the new location: jaegertracing.io_jaegers_crd.yaml . If there are
# inconsistencies between the files, this one is considered wrong.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: jaegers.jaegertracing.io
spec:
  group: jaegertracing.io
  names:
    kind: Jaeger
    listKind: JaegerList
    plural: jaegers
    singular: jaeger
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
