apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: k12
spec:
  strategy: production
  ingress:
    enabled: true
  storage:
    type: elasticsearch
    dependencies:
    enabled: false
    #schedule: "55 23 * * *"
    options:
      es:
        server-urls: http://192.168.0.249:9200

