apiVersion: v1
kind: Pod
metadata:
  labels:
    component: k12mgr
  name: k12mgr-pod
  namespace: micro
spec:
  containers:
    - image: nginx:1.15.12
      imagePullPolicy: IfNotPresent
      name: k12mgr
      ports:
        - containerPort: 8080
          hostPort: 8080
      volumeMounts:
        - mountPath: /www
          name: k12mgr-static-vol
        - mountPath: /etc/nginx/conf.d
          name: k12mgr-config-vol
  volumes:
    - name: k12webtest-static-vol
      hostPath:
        path: /home/ubuntu/k12mgr/dist
    - name: k12mgr-config-vol
      hostPath:
        path: /home/ubuntu/k12mgr/config
  nodeName: microweb
