apiVersion: v1
kind: Pod
metadata:
  labels: 
    component: web
  name: web-pod
  namespace: micro
spec: 
  containers: 
  - command: 
    - /micro
    - --web_address=:8082
    - --server_name=k12web
    - --registry=consul
    - --registry_address=192.168.1.151:8500 
    - --register_interval=20
    - --register_ttl=30
    - web
    - --namespace=hikedu.k12.common.api
    image: microhq/micro 
    imagePullPolicy: IfNotPresent
    name: microweb
  hostNetwork: true
  nodeName: microweb
