apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-backup
  labels:
    pvname: pv-backup
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.249
    path: "/mnt/backup"
