apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-filer
  labels:
    pvname: pv-filer
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.249
    path: "/mnt/data/filer"
