apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-log
  labels:
    pvname: pv-log
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.249
    path: "/mnt/log"
