kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-log
  namespace: micro
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      pvname: pv-log
