apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simplest
  namespace: micro
spec:
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://192.168.0.249:9200

