apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-filer
  labels:
    alicloud-pvname: pv-filer
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  flexVolume:
    driver: "alicloud/nas"
    options:
      server: "364c44947f-dty77.cn-shanghai.nas.aliyuncs.com"   
      path: "/data/filer"
      vers: "4.0"
