apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-seaweedvol
  labels:
    alicloud-pvname: pv-seaweedvol
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  flexVolume:
    driver: "alicloud/nas"
    options:
      server: "364c44947f-dty77.cn-shanghai.nas.aliyuncs.com"   
      path: "/data/seaweedvol"
      vers: "4.0"
