kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-backup
  namespace: k12
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      alicloud-pvname: pv-backup
