kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-filer
  namespace: k12
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      alicloud-pvname: pv-filer
