kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-consul
  namespace: k12
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      alicloud-pvname: pv-consul
