apiVersion: v1
kind: Service
metadata: 
  name: consul-svc
  namespace: k12
  labels: 
    app: consul
spec:
  type: NodePort
  ports:
  - port: 8500
    targetPort: 8500
    nodePort: 30850
    protocol: TCP
    name: http
  selector:
    app: consul
