apiVersion: v1
kind: Service
metadata: 
  name: microweb-svc
  namespace: k12
  labels: 
    app: microweb
spec:
  type: NodePort
  ports:
  - port: 8082
    targetPort: 8082
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: microweb
