apiVersion: v1
kind: Service
metadata:
  name: seaweed
  namespace: k12
  labels:
    app: seaweed
spec:
  clusterIP: None
  ports:
    - name: http
      port: 9333
      targetPort: 9333
    - name: grpc
      port: 19333
      targetPort: 19333
  selector:
    app: seaweed
